//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSSStoresApp.EFBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class svssstores_itemgroup
    {
        public svssstores_itemgroup()
        {
            this.svssstores_itemmaster = new HashSet<svssstores_itemmaster>();
        }
    
        public long itemgroup_id { get; set; }
        public string itemgroup_groupname { get; set; }
    
        public virtual ICollection<svssstores_itemmaster> svssstores_itemmaster { get; set; }
    }
}
