//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSSStoresApp.EFBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class svssstores_stockissuemaster
    {
        public svssstores_stockissuemaster()
        {
            this.svssstores_stockissuedetail = new HashSet<svssstores_stockissuedetail>();
        }
    
        public long stockissuemaster_Id { get; set; }
        public Nullable<System.DateTime> stockissuemaster_issuedate { get; set; }
        public string stockissuemaster_particualrs { get; set; }
        public string stockissuemaster_issuedto { get; set; }
        public Nullable<int> stockissuemaster_transfertype { get; set; }
        public Nullable<int> stockissuemaster_issuetype { get; set; }
        public string stockissuemaster_number { get; set; }
    
        public virtual ICollection<svssstores_stockissuedetail> svssstores_stockissuedetail { get; set; }
    }
}
