//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSSStoresApp.EFBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class svssstores_stockissuedetail
    {
        public long stockissuedetail_Id { get; set; }
        public long stockissuedetail_masterid { get; set; }
        public long stockissuedetail_itemid { get; set; }
        public Nullable<int> stockissuedetail_transfertype { get; set; }
        public Nullable<int> stockissuedetail_issuetype { get; set; }
        public string stockissuedetail_remarks { get; set; }
        public decimal stockissuedetail_Qty { get; set; }
    
        public virtual svssstores_itemmaster svssstores_itemmaster { get; set; }
        public virtual svssstores_stockissuemaster svssstores_stockissuemaster { get; set; }
    }
}
