//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSSStoresApp.EFBO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SVSSStoresEntities : DbContext
    {
        public SVSSStoresEntities()
            : base("name=SVSSStoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<svssstores_itemgroup> svssstores_itemgroup { get; set; }
        public DbSet<svssstores_itemmaster> svssstores_itemmaster { get; set; }
        public DbSet<svssstores_stockdetail> svssstores_stockdetail { get; set; }
        public DbSet<svssstores_stockissuedetail> svssstores_stockissuedetail { get; set; }
        public DbSet<svssstores_stockissuemaster> svssstores_stockissuemaster { get; set; }
        public DbSet<svssstores_stockmaster> svssstores_stockmaster { get; set; }
    }
}
