//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVSSStoresApp.EFBO
{
    using System;
    using System.Collections.Generic;
    
    public partial class svssstores_stockdetail
    {
        public long stockdetail_id { get; set; }
        public long stockdetail_masterid { get; set; }
        public long stockdetail_itemId { get; set; }
        public Nullable<int> stockdetail_transfertype { get; set; }
        public string stockdetail_remarks { get; set; }
        public Nullable<int> stockdetail_purchasertype { get; set; }
        public decimal stockdetail_qty { get; set; }
        public Nullable<decimal> stockdetail_unitprice { get; set; }
    
        public virtual svssstores_itemmaster svssstores_itemmaster { get; set; }
        public virtual svssstores_stockmaster svssstores_stockmaster { get; set; }
    }
}
